<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".git\COMMIT_EDITMSG" />
    <None Include=".git\config" />
    <None Include=".git\description" />
    <None Include=".git\HEAD" />
    <None Include=".git\hooks\applypatch-msg.sample" />
    <None Include=".git\hooks\commit-msg.sample" />
    <None Include=".git\hooks\fsmonitor-watchman.sample" />
    <None Include=".git\hooks\post-update.sample" />
    <None Include=".git\hooks\pre-applypatch.sample" />
    <None Include=".git\hooks\pre-commit.sample" />
    <None Include=".git\hooks\pre-merge-commit.sample" />
    <None Include=".git\hooks\pre-push.sample" />
    <None Include=".git\hooks\pre-rebase.sample" />
    <None Include=".git\hooks\pre-receive.sample" />
    <None Include=".git\hooks\prepare-commit-msg.sample" />
    <None Include=".git\hooks\push-to-checkout.sample" />
    <None Include=".git\hooks\sendemail-validate.sample" />
    <None Include=".git\hooks\update.sample" />
    <None Include=".git\index" />
    <None Include=".git\info\exclude" />
    <None Include=".git\logs\HEAD" />
    <None Include=".git\logs\refs\heads\master" />
    <None Include=".git\objects\00\3705298f83cec368c95c65d4f09857d23f3539" />
    <None Include=".git\objects\02\7fdf5b7d4b24737866f9c08566b79948fc7895" />
    <None Include=".git\objects\08\047e624cb33a9a4b263ff2a3d0c43101c5bbeb" />
    <None Include=".git\objects\0c\ea1c46081906cab81b546c24902df148d4b46c" />
    <None Include=".git\objects\10\f960612a2e4ebcbe702d4b9176099205ab4b0c" />
    <None Include=".git\objects\18\891835304320dc7e92ffece0d2bb44c71e4fd8" />
    <None Include=".git\objects\1c\389948b9d572c58cdb180dba8707b669614cb0" />
    <None Include=".git\objects\1d\340d4e9540b6d5b80a8c3e5baf8cf8ebb411dd" />
    <None Include=".git\objects\22\d6344d56588ecacfe277acf2b55a7cefe39dc7" />
    <None Include=".git\objects\26\11587f1e9690b26bff04c665d5c460b730f4cd" />
    <None Include=".git\objects\29\5d99182550303f133a4729b278d449906473e0" />
    <None Include=".git\objects\2d\1b344b7fd18dd646cb1b80ae971e75feebed7d" />
    <None Include=".git\objects\34\267e0a5e0dd95dfc6355ae14fde54b797d229e" />
    <None Include=".git\objects\36\b5f7a37c47e70914898fc04fd81275ca32eb10" />
    <None Include=".git\objects\39\7786757ebe409b4fecab741a86eee33d22b8df" />
    <None Include=".git\objects\3a\260ef4868f262c7b50358dee084f24c37c4c46" />
    <None Include=".git\objects\3a\e6d89a390fc5b82b4bbfbe46b4f3bd5723badc" />
    <None Include=".git\objects\3b\7a3ad62f946c1af6c13d664ee839bb52d704b2" />
    <None Include=".git\objects\3e\62fc314545f7f095de6dc2b5a91a57f1ba525f" />
    <None Include=".git\objects\3e\726ba33a4bbb4e4734e3f40c15362bafa00378" />
    <None Include=".git\objects\3e\96d1ce9b2c14824f9cd179ab0ee49f0860ae45" />
    <None Include=".git\objects\48\175f2876abba9006b73d5a77af637c9c82685e" />
    <None Include=".git\objects\48\918702157deed4e1c305dff52be72e512064ad" />
    <None Include=".git\objects\4b\592690455d5bf3f736d94b678340fd8a65390f" />
    <None Include=".git\objects\4d\6ec925e47f62a5182005f463277acb59c26bed" />
    <None Include=".git\objects\55\7d365db4188855723e1444944b298d96f9fa33" />
    <None Include=".git\objects\56\bec5d1f10acbfc2bc7e8b11d5d82d9e8b0bf1b" />
    <None Include=".git\objects\59\2c586ceae226d12f4b06a8897bf2d754d557f7" />
    <None Include=".git\objects\5a\2ce1adf22abeb7848de8469f7c91417e8e3a41" />
    <None Include=".git\objects\63\7574f319ef6439d3813d1c54c3886036915686" />
    <None Include=".git\objects\69\ab3ceb1ae28c6f0cc837d4e80935ca38cea657" />
    <None Include=".git\objects\72\b77ed27a5ef655a7847ef236d90ccd7f303713" />
    <None Include=".git\objects\74\2f38bf9a8106480c09cf969708b835565d67e8" />
    <None Include=".git\objects\76\033beda1f4a9ac229aa6182fdfbd80757a05f1" />
    <None Include=".git\objects\7c\e6d22d81adddcfd3316409b62337ffb105a678" />
    <None Include=".git\objects\7d\18248c1ddbe5c0a0e0e030ae3f79ba60dcef60" />
    <None Include=".git\objects\83\47b30b8aa4a93359fbea835c09e8354398df09" />
    <None Include=".git\objects\95\e67b32d8a796c4576fe590f9eaeb04c357e41a" />
    <None Include=".git\objects\96\a9831ecfb1cef4a77a36c82dbdde780fb54d9b" />
    <None Include=".git\objects\98\ec32a7e8f77a3f9118345fcb059ded760490d9" />
    <None Include=".git\objects\9c\01c8e641087e22c4da24e7be833559e670d380" />
    <None Include=".git\objects\9c\e0b0cb12dc6b2244c44802357a0038f2903d05" />
    <None Include=".git\objects\9e\6b83593221351541d93951aaea2d32e69853a0" />
    <None Include=".git\objects\9f\35f3061ed6fa6eb845d9098f257fb74231968b" />
    <None Include=".git\objects\a2\ebec375d6ab7a79c09b33eba6090c171a4fbe2" />
    <None Include=".git\objects\a3\d635ae3d6471495c12026b5070adc3dcdc13b1" />
    <None Include=".git\objects\a6\dccc6abecad2386955d77b0e0df40000b0b4a6" />
    <None Include=".git\objects\a9\24e9754d52c241462393960c6065991794166b" />
    <None Include=".git\objects\b1\00a37fc43dd41143c40449b7d3201792bb06bf" />
    <None Include=".git\objects\ba\979b3809bbd178a29f6ee227cfa7c19943751e" />
    <None Include=".git\objects\bc\731cf22211a52e5359ec4d89fa7a53aeb1f4ed" />
    <None Include=".git\objects\bd\2b9fa0139a699f073c7c8dcc407dca74e1d9e1" />
    <None Include=".git\objects\be\28060157e4fee007b987fa9d6dd7dde7e555e0" />
    <None Include=".git\objects\be\fa348940dfc5ca9a9ce7c172f8d9120e2d8fe2" />
    <None Include=".git\objects\c2\0442b30f05390eaa6c2613918c01f965b6d6eb" />
    <None Include=".git\objects\c5\a124940c15eebdcaee0b8f0695e634cd88c770" />
    <None Include=".git\objects\cc\22c3cdd24114527e2f1881e5889a43437f53b3" />
    <None Include=".git\objects\cf\af55401b118d0692ca1ac5079481987b3e8b76" />
    <None Include=".git\objects\d5\2d83c340034e7cf3fba75a29250ea220f919fc" />
    <None Include=".git\objects\d5\64d0bc3dd917926892c55e3706cc116d5b165e" />
    <None Include=".git\objects\d7\5ef8436d3ca8686e4ba85ab2983b4bada35291" />
    <None Include=".git\objects\de\970bbe905fa255af157ff6e142d111317b5f7d" />
    <None Include=".git\objects\e3\a3420fdd4c26f9490bf4aefbe481813d7af563" />
    <None Include=".git\objects\e6\1234f2eb44bb73620e97cb5e806e1c944914ab" />
    <None Include=".git\objects\e6\9de29bb2d1d6434b8b29ae775ad8c2e48c5391" />
    <None Include=".git\objects\e9\44987b8d3c3c40f9822195499240d952949ec9" />
    <None Include=".git\objects\e9\f42dbdb568d41898ac43d068ff2bc3bc0646a6" />
    <None Include=".git\objects\f1\0667242fc449f361c6d3de3da76b7261d384d1" />
    <None Include=".git\objects\f3\559629a7d46623711168ec57fd0e02a3883d06" />
    <None Include=".git\objects\f7\8cfbe4a431580c667316ee6f28f600089d5707" />
    <None Include=".git\objects\f9\8fb410a5cf873457e76ce96fe1332037646ff3" />
    <None Include=".git\objects\fe\200f76987e628e752f24c0b06434de4ce96978" />
    <None Include=".git\objects\ff\c0b4d8348e04c1f5058def3cea93aad4da61f1" />
    <None Include=".git\refs\heads\master" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".git\branches\" />
    <Folder Include=".git\objects\info\" />
    <Folder Include=".git\objects\pack\" />
    <Folder Include=".git\refs\tags\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
  </ItemGroup>

</Project>
